stages:
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  IMAGE_TAG2: noahding1214/webdav-s3:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker login -u noahding1214 -p $DOCKER_HUB_KEY

build:
  image: docker:23.0.6-dind
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker tag $IMAGE_TAG $IMAGE_TAG2
    - docker push $IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $IMAGE_TAG2
  only:
    - main
