region: "us-east-1"
access_key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
secret_key: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
bucket_name: "xxxxx"
endpoint: "https://cccc"
baseurl: "http://127.0.0.1"
port: "8080"