loglevel: "INFO"
region: "us-east-1"
access_key: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
secret_key: "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
bucket_name: "webdav"
endpoint: "https://s3.us-east-1.amazonaws.com"
baseurl: "http://127.0.0.1"
port: "8080"